### ISSUE TITLE
Finished levels are not saved [RetroFW]

### ISSUE THREAD

**Issue by szymor** [glebm/od-slitherlink#1]
After quitting the game, it shows no progress, even after finishing a few levels. It is quite disturbing, because it is hard to track the progress manually and switching the level to play is cumbersome in case of a few hundreds of available levels.

**Comment by glebm** [comment]
Ah, I guess we need to define these 3 constants to an absolute path

https://github.com/glebm/od-slitherlink/blob/9c0f376a63e096ce0fdf6978f04abe469d687afc/def.h#L35-L37

**Comment by szymor** [comment]
I will leave it to you as you were the first to port it to RetroFW. ;)

**Comment by glebm** [comment]
I don't have a RetroFW device at the moment, so PRs are welcome!

**Comment by szymor** [comment]
The feature is implemented and PR got merged so I close the ticket.
